---
title: Gabster
timezone: UTC
collections:
  brands:
    title: Brands
    output: true
  featured-service:
    title: Featured Service
    output: true
  footer:
    title: Footer
    output: true
  jumbotron:
    title: Jumbotron
    output: true
  media-coverage:
    title: Media Coverage
    output: true
  portfolio:
    title: Portfolio
    output: true
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  testimonials:
    title: Testimonials
    output: true
  trend:
    title: Trend
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: gabstersays
name: Gabster GFC
description: Fashion Consultant, Clothing Production, Indonesia Clothing Factory.
avatar: 
wa: 6281220836618
watext: Hi%20GABSTER,%20i%20need%20info%20for%20your%20services.
instagram: gabstersays
youtube: UCQjtAykgOU9OZHrXHlWrjHQ
facebook: gabstersays
disqus: 
google_analytics: 
url: http://gabstergfc.com
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
